#!/bin/bash

# Output
kanshi &

# ENVIRONMENT
# =========================================

# --- dirs
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_CONFIG_DIRS=/etc/xdg

export CARGO_HOME=$HOME/.local/share/cargo
export RUSTUP_HOME=$HOME/.local/share/rustup
export GRIM_DEFAULT_DIR=$HOME/Pictures/screenshots
export GOPATH=$HOME/.local/share/go
export OLLAMA_MODELS=$XDG_DATA_HOME/ollama/models

# --- some programms
export EDITOR=nvim
export VISUAL=nvim
export TERM=footclient

export PAGER=less
export MANPAGER="nvim +Man!"

export BROWSER=firefox

export GCC_COLORS=auto
export CLICOLOR=1

export CARGO_TERM_COLOR=always

export LESS=-R
export LESSHISTFILE=-

# --- WAYLAND
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland,x11
export SDL_VIDEO_DRIVER=wayland,x11
export GDK_BACKEND=wayland,x11
export ELECTRON_OZONE_PLATFORM_HINT=auto

# setting some XDG stuff for better communication
export XDG_CURRENT_DESKTOP=river
export XDG_SESSION_DESKTOP=river
export XDG_CURRENT_SESSION_TYPE=wayland
export XDG_SESSION_TYPE=wayland

# for systems without seatd (from systemd)
export LIBSEAT_BACKEND=logind;

export WLR_RENDERER=vulkan

export XCURSOR_THEME=Bibata-Modern-Classic
export XCURSOR_SIZE=32
export XCURSOR_PATH=/usr/share/icons:$HOME/.local/share/icons
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_STYLE_OVERRIDE=kvantum
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# --- SCALING
export GDK_SCALE=1
export GDK_DPI_SCALE=1.33

# QT
export QT_SCALE_FACTOR=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_USE_PHYSICAL_DPI=1
export QT_ENABLE_HIGHDPI_SCALING=1
export QT_WAYLAND_DISABLE_WINDOW_DECORATION=1

# XWayland (fix blurry X11 apps)
export XWAYLAND_NO_GLAMOR=0

# Electron fixes
export ELECTRON_DISABLE_GPU_SANDBOX=1
export ELECTRON_FORCE_DEVICE_SCALE_FACTOR=1


# basic commmand
# =========================================
riverctl map normal Super M exit
riverctl map normal Super Space toggle-float


# spawn programms
# =========================================
riverctl map normal Super Return spawn $TERM
riverctl map normal Super W spawn 'GDK_DPI_SCALE=1.33 firefox'
riverctl map normal Super+Shift W spawn 'GDK_DPI_SCALE=1.33 firefox --private-window'
riverctl map normal Super R spawn fuzzel


# window commands
# =========================================
riverctl map normal Super Q close

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# move window to top of stack
riverctl map normal Super Z zoom

riverctl map -repeat normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map -repeat normal Super L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

riverctl map normal Super F toggle-fullscreen


# floating windows
# =========================================
riverctl map -repeat normal Super+Alt H move left 100
riverctl map -repeat normal Super+Alt J move down 100
riverctl map -repeat normal Super+Alt K move up 100
riverctl map -repeat normal Super+Alt L move right 100

riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

riverctl map -repeat normal Super+Alt+Shift H resize horizontal -100
riverctl map -repeat normal Super+Alt+Shift J resize vertical 100
riverctl map -repeat normal Super+Alt+Shift K resize vertical -100
riverctl map -repeat normal Super+Alt+Shift L resize horizontal 100


# mouse
# =========================================
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float


# tags (workspaces)
# =========================================
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
    riverctl map normal Super+Control $i toggle-focused-tags $tags
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags


# Layout
# =========================================
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Passthrough
# =========================================
riverctl declare-mode passthrough
riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal


# Media
# =========================================
riverctl map -repeat normal None XF86AudioRaiseVolume  spawn "wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"
riverctl map -repeat normal None XF86AudioLowerVolume  spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
riverctl map normal None XF86AudioMute spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
riverctl map normal None XF86AudioPlay spawn 'playerctl play-pause'
riverctl map normal None XF86AudioPrev spawn 'playerctl previous'
riverctl map normal None XF86AudioNext spawn 'playerctl next'


# Functions
# =========================================

# Screenshot
riverctl map normal Super S spawn 'grim -g "$(slurp)" - | wl-copy'

# Tesseract text copy
riverctl map normal Super T spawn 'grim -g "$(slurp)" - | tesseract -l eng+deu stdin stdout 2>/dev/null | wl-copy'

# open wl-paste in nvim
riverctl map normal Super N spawn "wl-paste > /tmp/cfn.txt && $TERM -e nvim /tmp/cfn.txt"

# open cliphist in fuzzel
riverctl map normal Super C spawn "cliphist list | fuzzel -d | cut -d ' ' -f 1 | cliphist decode | wl-copy"

# Colors & Border
# =========================================
riverctl background-color 0x11111b
riverctl border-color-focused 0xcba6f7
riverctl border-color-unfocused 0x313244
riverctl border-color-urgent 0xf38ba8
riverctl border-width 4


# Keyboard
# =========================================
riverctl set-repeat 50 250
riverctl keyboard-layout -variant altgr-intl us


# Cursor
# =========================================
riverctl focus-follows-cursor normal
riverctl hide-cursor timeout 10000
riverctl hide-cursor when-typing disabled
riverctl set-cursor-warp on-focus-change
riverctl xcursor-theme Bibata-Modern-Classic 32


# Rules
# =========================================
riverctl rule-add -app-id "bar" csd
riverctl rule-add -app-id 'float*' -title 'foo' float


# EXECUTE
# =========================================

killall playerctld
playerctld daemon

# killall blueman-applet
# blueman-applet &

cliphist wipe
wl-paste --watch cliphist store &
waybar &
mako &
foot -s &
awww-daemon &

# swayidle -w \
#     timeout 1200 'notify-send "Swayidle" "going to sleep in 10min"' \
#     timeout 1800 'zzz' &


# Layout generator
# =========================================
riverctl attach-mode top
riverctl default-layout rivertile
riverctl rule-add ssd
rivertile -view-padding 4 -outer-padding 4 -main-ratio 0.5 &
exec dbus-update-activation-environment DISPLAY I3SOCK SWAYSOCK WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
