#!/bin/bash

# ENVIRONMENT
# =========================================
export EDITOR=nvim
export VISUAL=nvim
export TERM=foot

export XDG_CONFIG_HOME=$HOME/.config/
export XDG_CACHE_HOME=$HOME/.cache/
export XDG_DATA_HOME=$HOME/.local/share/
export XDG_STATE_HOME=$HOME/.local/state/
export XDG_DATA_DIRS=/usr/local/share/:/usr/share/
export XDG_CONFIG_DIRS=/etc/xdg/
export CARGO_HOME=$HOME/.local/share/cargo/
export RUSTUP_HOME=$HOME/.local/share/rustup/
export GRIM_DEFAULT_DIR=$HOME/Pictures/screenshots/
export GOPATH=$HOME/.local/share/go

# themes
export XCURSOR_THEME=Bibata-Modern-Classic
export XCURSOR_SIZE=32
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_STYLE_OVERRIDE=kvantum
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export GDK_SCALE=2

# wayland
export MOZ_ENABLE_WAYLAND=1
export WLR_RENDERER=vulkan
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export GDK_BACKEND=wayland
export ELECTRON_OZONE_PLATFORM_HINT=auto
export OLLAMA_MODELS=$XDG_DATA_HOME/ollama/models


# basic commmand
# =========================================
riverctl map normal Super+Shift E exit
riverctl map normal Super Space toggle-float


# spawn programms
# =========================================
riverctl map normal Super Return spawn footclient
riverctl map normal Super Z spawn 'footclient zellij'
riverctl map normal Super W spawn firefox
riverctl map normal Super+Shift W spawn 'firefox --private-window'
riverctl map normal Super R spawn fuzzel
riverctl map normal Super E spawn pcmanfm-qt
riverctl map normal Super O spawn obsidian


# window commands
# =========================================
riverctl map normal Super Q close

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# move window to top of stack
riverctl map normal Super T zoom

riverctl map -repeat normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map -repeat normal Super L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

riverctl map normal Super F toggle-fullscreen


# floating windows
# =========================================
riverctl map -repeat normal Super+Alt H move left 100
riverctl map -repeat normal Super+Alt J move down 100
riverctl map -repeat normal Super+Alt K move up 100
riverctl map -repeat normal Super+Alt L move right 100

riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

riverctl map -repeat normal Super+Alt+Shift H resize horizontal -100
riverctl map -repeat normal Super+Alt+Shift J resize vertical 100
riverctl map -repeat normal Super+Alt+Shift K resize vertical -100
riverctl map -repeat normal Super+Alt+Shift L resize horizontal 100


# mouse
# =========================================
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float


# tags (workspaces)
# =========================================
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
    riverctl map normal Super+Control $i toggle-focused-tags $tags
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags


# Layout
# =========================================
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"


# Media
# =========================================
riverctl map -repeat normal None XF86AudioRaiseVolume  spawn "wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"
riverctl map -repeat normal None XF86AudioLowerVolume  spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
riverctl map normal None XF86AudioMute spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
riverctl map normal None XF86AudioPlay spawn 'playerctl play-pause'
riverctl map normal None XF86AudioPrev spawn 'playerctl previous'
riverctl map normal None XF86AudioNext spawn 'playerctl next'


# Functions
# =========================================

# TODO: Screenshot

# TODO: Tesseract text copy
riverctl map normal Super+Shift T spawn 'grim -g "$(slurp)" - | tesseract-ocr stdin stdout | wl-copy notify-send -t 3000 -u low "Textshot" "$(wl-paste)"'

# open wl-paste in nvim
riverctl map normal Super N spawn 'wl-paste > /tmp/cfn.txt; footclient nvim /tmp/cfn.txt'

# open cliphist in fuzzel
riverctl map normal Super C spawn $'cliphist list | fuzzel -d | head -n 1 | awk \'{printf "%s", $1}\' | cliphist decode | wl-copy'


# Output
# =========================================
wlr-randr --output DP-2 --mode 3840x2160 --pos 1440,0
wlr-randr --output HDMI-A-1 --mode 1920x1080 --pos 0,0 --transform 90 --scale 0.75

# Colors & Border
# =========================================
riverctl background-color 0x11111b
riverctl border-color-focused 0xcba6f7
jiverctl border-color-unfocused 0x313244
riverctl border-color-urgent 0xf38ba8
riverctl border-width 4


# Keyboard
# =========================================
riverctl set-repeat 50 300
riverctl keyboard-layout -variant altgr-intl us


# Cursor
# =========================================
riverctl focus-follows-cursor normal
riverctl hide-cursor timeout 10000
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-focus-change
riverctl xcursor-theme Bibata-Modern-Classic 32


# Rules
# =========================================
riverctl rule-add -app-id "bar" csd
riverctl rule-add -app-id 'float*' -title 'foo' float


# EXECUTE
# =========================================
source '/home/niels/.local/share/cargo/env'

killall pipewire
pipewire &

killall mpd
mpd &

killall transmission-daemon
transmission-daemon &

killall syncthing
syncthing --no-browser &

killall mpDris2
mpDris2 &

cliphist wipe
wl-paste --watch cliphist store &
$(sleep 1; waybar) &
mako &
foot -s &

# swayidle -w \
#     timeout 1200 'wlr-randr --output HDMI-A-1 --off && wlr-randr --output DP-2 --off' \
#     resume 'wlr-randr --output DP-2 --on && wlr-randr --output DP-2 --mode 3840x2160 --pos 1440,0 && wlr-randr --output HDMI-A-1 --on && wlr-randr --output HDMI-A-1 --mode 1920x1080 --pos 0,0 --transform 90 --scale 0.75' &
swayidle -w \
    timeout 1200 'notify-send "Swayidle" "going to sleep in 10min"' \
    timeout 1800 'zzz' &


# Layout generator
# =========================================
riverctl attach-mode top
riverctl default-layout rivertile
rivertile -view-padding 4 -outer-padding 4 -main-ratio 0.5 &

